name: EarPhoneMusic4

options:
  bundleIdPrefix: app.takaoka.harusuke
  deploymentTarget:
    iOS: "17.5"
  developmentLanguage: en
  xcodeVersion: "15.4"
  createIntermediateGroups: true

targets:
  EarPhoneMusic4:
    type: application
    platform: iOS

    settings:
      base:
        DEVELOPMENT_TEAM: 5B2NQ74986
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: true

    sources:
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
          - "project.yml"
